[phases.setup]
nixPkgs = ["...", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "NODE_OPTIONS=\"--dns-result-order=ipv4first\" npx prisma db push --accept-data-loss && NODE_OPTIONS=\"--dns-result-order=ipv4first\" node dist/main"
